backend/models/Garden.php
<?php

namespace app\models;

use common\config\ProjectConstants;
use common\models\tables\Apple;
use yii\base\Model;
use yii\db\Exception;

/**
 * Class Garden
 * Serves for manipulation with different data connected with table `apple`.
 * @package app\models
 */
class Garden extends Model
{
    /**
     * Generates new records in table `apple` due to given number.
     * @param $number
     * @throws Exception
     */
    public function generateApples($number)
    {
        while ($number) {

            $apple = new Apple();
            if (!$apple->save(false)) {
                throw new Exception('Яблоко пропало и не записано в базу данных!');
            }
            $apples[] = $apple;
            $number--;
        }
    }

    /**
     * Composes text for a model description on /garden/index.
     * @param $model
     * @return string
     */
    public static function getText($model)
    {
        $size = '';

        switch ($model->size) {
            case 1:
                $size = ' целое яблоко';
                break;
            case 0.75:
                $size = ' почти целое яблоко';
                break;
            case 0.5:
                $size = ' половина яблока';
                break;
            case 0.25:
                $size = ' маленький кусочек яблока';
                break;
            case 0:
                $size = ' уже и не яблоко';
                break;
        }

        $color = '';

        switch ($model->color) {
            case 'green':
                $color = 'зеленый';
                break;
            case 'yellow':
                $color = 'желтый';
                break;
            case 'red':
                $color = 'красный';
                break;
            default:
                $color = $model->color;
        }

        return <<<EOL
Это {$size}. <br />
Цвет: {$color}. <br />
EOL;
    }

}

backend/controllers/GardenController.php
<?php

namespace backend\controllers;

use app\models\Garden;
use common\config\ProjectConstants;
use phpDocumentor\Reflection\Types\Integer;
use yii\base\DynamicModel;
use yii\data\ActiveDataProvider;
use yii\db\Exception;
use yii\web\Controller;
use common\models\tables\Apple;

/**
 * Class GardenController manages all apples' operations.
 * @package backend\controllers
 */
class GardenController extends Controller
{

    /**
     * Displays all aplles that exists in db table apples with status 1,
     * allows generate new records.
     * @return string
     * @throws Exception
     */
    public function actionIndex()
    {
        $model = new DynamicModel(['number']);
        $model
            ->addRule('number', 'integer', [
                'min' => ProjectConstants::APPLE_MIN_NUMBER,
                'max' => ProjectConstants::APPLE_MAX_NUMBER
            ])
            ->addRule('number', 'default', ['value' => 0]);

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
            $number = (int)\Yii::$app->request->post()['DynamicModel']['number'];

            if ($number) {
                (new Garden())->generateApples($number);
            }
        }


        $dataProvider = new ActiveDataProvider([
            'query' => Apple::find()->where(['status' => ProjectConstants::STATUS_ACTIVE])->orderBy(['created_at' => SORT_DESC]),
            'pagination' => [
                'pageSize' => 100,
            ]
        ]);

        return $this->render('index', [
            'model' => $model,
            'dataProvider' => $dataProvider,

        ]);

    }

    /**
     * Sets inactive status (0) to all rows in table `apple`.
     */
    public function actionDeleteAll()
    {
        //Apple::deleteAll(); use it if you really need delete all the records from db

        $message = 'Все яблоки удалены';
        $type = 'success';

        $command = \Yii::$app->db->createCommand('UPDATE apple SET status = 0 WHERE status = 1');
        try {
            $command->execute();
        } catch (\Exception $exception) {
            $message = 'Удаление не удалось. Причина: <br/>' . $exception->getMessage();
            $type = 'error';
        }

        \Yii::$app->session->setFlash($type, $message);
        $this->redirect('/admin/garden');
    }


    /**
     * Proceeds different types of form submit from /garden/index view.
     * @param string $id
     */
    public function actionProceedApple(string $id)
    {
        $apple = Apple::findOne($id);
        $typeButton = \Yii::$app->request->post()['button'];

        if ($typeButton === 'fall') {
            $this->fall($apple);
        }

        if ($typeButton === 'eat') {
            $this->eat($apple);
        }

        if ($apple->status) {
            echo $this->renderPartial('_appleListView', [
                'model' => $apple,
            ]);
        } else {
            \Yii::$app->session->addFlash('error', 'Яблоко ' . $apple->id . ' съедено');
            $this->redirect('/admin/garden');
        }

    }

    /**
     * Defines that apple was fallen from a tree.
     * @param Apple $apple
     */
    public function fall(Apple $apple)
    {
        $apple->fallToGround();
        $apple->save();
    }

    /**
     * Checks if an apple is eatable and corrects size according to new data.
     * @param $apple
     * @param int $percentage
     */
    public function eat($apple, $percentage = 0)
    {
        $percentage = (int)\Yii::$app->request->post()['Apple']['size'];

        try {
            $apple->eat($percentage);
        } catch (\Exception $exception) {
            \Yii::$app->session->addFlash('error', $exception->getMessage());
            $this->redirect('/admin/garden');
        }
    }

}

backend/views/garden/_appleListView.php
<?php

use app\models\Garden;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\helpers\Url;

/**
 * @var $model \common\models\tables\Apple
 */

?>
<div class="card" style="width: 18rem;">
    <h5 class="card-title"><?php echo 'Яблоко №' . $model->id ?></h5>
    <?php

    Pjax::begin([
        'id' => $model->id,
        'enablePushState' => false,
        'timeout' => 100000,
    ]);


    $form = ActiveForm::begin([
        'action' => Url::to(['garden/proceed-apple', 'id' => $model->id]),
        'options' => [
            'data-pjax' => true,
            'class' => 'form-oneapple'
        ],
        'method' => 'post',
        'id' => 'apples' . $model->id,
    ]);

    if ($model->is_on_tree) {
        echo Html::submitButton('Уронить на землю', ['class' => 'btn btn-primary', 'name' => 'button', 'value' => 'fall']);
    } else {

        echo $form
            ->field($model, 'size')
            ->label('Съесть?')
            ->dropDownList([
                25 => 'Откусить четверть яблока',
                50 => 'Откусить половину',
                75 => 'Съесть три четверти',
                100 => 'Съесть всё',
            ],
                ['options' => [
                    25 => ['Selected' => true]
                ]
                ]
            );

        echo Html::submitButton('Откусить', ['class' => 'btn btn-primary', 'name' => 'button', 'value' => 'eat']);

    }

    ActiveForm::end();

    ?>

    <div class="card-body">
        <p class="card-text"><?php echo Garden::getText($model); ?></p>
    </div>

    <?php

    Pjax::end();

    ?>


    <!-- <img class="card-img-top" src="..." alt="Card image cap">-->
    <!--<div class="card-body">
        <h5 class="card-title"><?php /*echo $model->color */ ?></h5>
        <p class="card-text"><?php /*echo Garden::getText($model); */ ?></p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>-->
</div>

backend/views/garden/index.php
<?php

/**
 * @var $model \common\models\tables\Apple
 * @var $dataProvider
 */

use backend\assets\GardenAsset;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\widgets\ListView;
use common\config\ProjectConstants;
use common\widgets\Alert;

GardenAsset::register($this);

?>

<?php

echo Alert::widget();

$min = ProjectConstants::APPLE_MIN_NUMBER;
$max = ProjectConstants::APPLE_MAX_NUMBER;

$placeholder = <<< EOL
Введите текст от {$min} до {$max}
EOL;

$form = ActiveForm::begin(); ?>

<?= $form->field($model, 'number')->label('Количество яблок')->input('integer', ['placeholder' => $placeholder]); ?>

<div class="form-group">
    <?= Html::submitButton('Получить', ['class' => 'btn btn-primary']) ?>
    <?= Html::a('Удалить все', '/admin/garden/delete-all', ['class' => 'btn btn-primary']) ?>
</div>

<?php ActiveForm::end();

?>


<?php

$template = <<< EOL
<div id="content">
    <div class="appleSum">{summary}</div>
    <div class="applePager">{pager}</div>
    <div class="appleItems">{items}</div>
</div>
EOL;

?>

<?php echo ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_appleListView',
    'layout' => $template,
    'id' => 'applesCards'
]);

?>